#!/bin/sh

rm -rf ./vim ./xmonad
mkdir ./vim ./xmonad

cp ~/.Xdefaults Xdefaults
cp ~/.vimrc vimrc
cp ~/.zshrc zshrc
cp ~/.xmodmap xmodmap
cp ~/.xbindkeysrc xbindkeysrc
cp ~/.xsession xsession
cp -r ~/.vim/* ./vim/
cp ~/.xmonad/xmonad.hs ./xmonad
cp ~/.gitconfig gitconfig
cp ~/.screenrc screenrc
cp ~/.xmobarrc xmobarrc
